---
title: "Lab 06 - Functions and iterations"
author: "MINGXI JIANG"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
str(diamonds)
table(clarity = diamonds$clarity)
summary(diamonds)
plot(diamonds$length_mm, diamonds$width_mm, main = "Length vs. Width", xlab = "Length (mm)", ylab = "Width (mm)")

```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?
mean_table_width <- mean(diamonds$table_mm)
print(mean_table_width)







# table_mm arithmetic mean within each clarity category
library(dplyr)
diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)
mean_table_width_by_clarity <- diamonds %>%
  group_by(clarity) %>%
  summarize(mean_table_mm = mean(table_mm))
print(mean_table_width_by_clarity)




```

_they have different variation in different table length._

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command
gmean <- function(x) {if (length(x) == 0) {stop("Input vector is empty")}
if (any(x <= 0)) {stop("Input vector contains non-positive values")}
ln_values <- log(x)
ln_mean <- mean(ln_values)
geometric_mean <- exp(ln_mean)
return(geometric_mean)}
data <- c(1, 2, 4, 8, 16)
result <- gmean(data)
cat("Geometric Mean:", result, "\n")







```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
